//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstRepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ShipAddress_City { get; set; }
        public string ShipAddress_Street { get; set; }
        public string ShipAddress_Country { get; set; }
        public string ShipAddress_PostCode { get; set; }
        public string InvoiceAddress_City { get; set; }
        public string InvoiceAddress_Street { get; set; }
        public string InvoiceAddress_Country { get; set; }
        public string InvoiceAddress_PostCode { get; set; }
        public bool IsRemoved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
